esphome:
  name: presence-sensor
  friendly_name: presence-sensor

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "utmYBjWAI1uV7/qyZuBOGzbUmBdFV3ICbfte01tIOOU="

ota:
  - platform: esphome
    password: "7179f15935938b2f0c766d75f86799ac"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Presence-Sensor Fallback Hotspot"
    password: "8f2B2udfgZQd"

captive_portal:

uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO18
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: uart_bus

number:
  ## Set Up Radar Gate Configuratio
  - platform: ld2410
    timeout:
      name: Radar Timeout
    light_threshold:
      name: Radar Light Threshold
    max_move_distance_gate:
      name: Radar Max Move Distance
    max_still_distance_gate:
      name: Radar Max Still Distance
    g0_move_threshold:
      name: g0 move threshold
    g0_still_threshold:
      name: g0 still threshold
    g1_move_threshold:
      name: g1 move threshold
    g1_still_threshold:
      name: g1 still threshold
    g2_move_threshold:
      name: g2 move threshold
    g2_still_threshold:
      name: g2 still threshold
    g3_move_threshold:
      name: g3 move threshold
    g3_still_threshold:
      name: g3 still threshold
    g4_move_threshold:
      name: g4 move threshold
    g4_still_threshold:
      name: g4 still threshold
    g5_move_threshold:
      name: g5 move threshold
    g5_still_threshold:
      name: g5 still threshold
    g6_move_threshold:
      name: g6 move threshold
    g6_still_threshold:
      name: g6 still threshold
    g7_move_threshold:
      name: g7 move threshold
    g7_still_threshold:
      name: g7 still threshold
    g8_move_threshold:
      name: g8 move threshold
    g8_still_threshold:
      name: g8 still threshold

  # Setting ending of zone 1 occupancy
  - platform: template
    name: "Radar End Zone 1"
    id: radar_z1_end
    unit_of_measurement: "in"
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 4
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG

  # Setting ending of zone 2 occupancy
  - platform: template
    name: "Radar End Zone 2"
    id: radar_z2_end
    unit_of_measurement: "in"
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 14
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG

  # Setting ending of zone 3 occupancy
  - platform: template
    name: "Radar End Zone 3"
    id: radar_z3_end
    unit_of_measurement: "in"
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 39
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG

text_sensor:
  - platform: ld2410
    version:
      name: Radar Firmware Version
    mac_address:
      name: Radar Mac Address

sensor:
  - platform: ld2410
    moving_distance:
      name : Moving Distance
      id: moving_distance
    still_distance:
      name: Still Distance
      id: still_distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Radar Detection Distance
      id: radar_detection_distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy

binary_sensor:
  - platform: ld2410
    has_target:
      name: Radar Presence
      id: radar_has_target
    has_moving_target:
      name: Radar Moving Target
    has_still_target:
      name: Radar Still Target

  ## Set Up Radar Zones Based On Distance
  - platform: template
    name: "Radar Zone 1 Occupancy"
    device_class: occupancy
    icon: mdi:motion-sensor
    lambda: |-
      if ((id(radar_has_target).state) && (id(radar_detection_distance).state < (id(radar_z1_end).state * 2.54))) {
        return true;
      } else {
        return false;
      }

  - platform: template
    name: "Radar Zone 2 Occupancy"
    device_class: occupancy
    icon: mdi:motion-sensor
    lambda: |-
      if ((id(radar_has_target).state) && (((id(radar_z1_end).state * 2.54) < id(radar_detection_distance).state) && (id(radar_detection_distance).state < (id(radar_z2_end).state * 2.54)))) {
        return true;
      } else {
        return false;
      }

  - platform: template
    name: "Radar Zone 3 Occupancy"
    device_class: occupancy
    icon: mdi:motion-sensor
    lambda: |-
      if ((id(radar_has_target).state) && (((id(radar_z2_end).state * 2.54) < id(radar_detection_distance).state) && (id(radar_detection_distance).state < (id(radar_z3_end).state * 2.54)))) {
        return true;
      } else {
        return false;
      }

  - platform: gpio
    pin: GPIO4
    name: GPIO Output
    id: gpio_output

button:
  - platform: restart
    icon: mdi:restart
    name: "Restart ESP"

  - platform: ld2410
    factory_reset:
      name: "Radar Factory Reset"
    restart:
      name: "Radar Restart"
    query_params:
      name: query parameters

switch:
  - platform: ld2410
    bluetooth:
      name: "Radar Bluetooth"
    engineering_mode:
      name: "Radar Engineering Mode"
    filter_out_still:
      name: "Radar Filter Still"
    filter_out_moving:
      name: "Radar Filter Move"

select:
  - platform: ld2410
    distance_resolution:
      name: "Radar Distance Resolution"
    baud_rate:
      name: "Radar Baud Rate"
    light_function:
      name: "Radar Light Function"
    out_pin_level:
      name: "Radar Out Pin Level"
